# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c0ccde54da53c004a6e7a64dbb6233429c6c8750496ee84b4828b3cac52fbeb5e80c907a3a28b481704ca88e336fb4c16c3f27655a8efa3e872ca46d4427bd8

test:
  secret_key_base: a3e9904dabec8d474763007133b8baeb0a0dafa3fea45c2e3e05387a1316aa8ea1d70defeb1236716d60a42ddf451a401fdea3a4019a4fb32e3b279b81debd41

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
